Fix and enhance CLI release workflow (#1613)
* add workflow to build registry with RHBQ

* fix: changes to build from right sources

diff --git a/.github/workflows/cli-release-macos.yaml b/.github/workflows/cli-release-macos.yaml
--- a/.github/workflows/cli-release-macos.yaml
+++ b/.github/workflows/cli-release-macos.yaml
@@ -1,37 +1,41 @@
 name: cli-release-build-native-macos
 
 on:
+  workflow_dispatch: {}
   release:
-    types: [created]
-  workflow_dispatch:
-    inputs:
-      tag_name:
-        description: 'Release Version (e.g. 2.0.0.Final)'
-        required: true
+    types: [released]
 
 jobs:
   build:
+    if: github.repository_owner == 'Apicurio'
     runs-on: macos-latest
     steps:
-    - uses: actions/checkout@v2
-    - name: Configure Environment (release)
-      if: github.event.release.tag_name != null
-      run: echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
-    - name: Configure Environment (dispatch)
-      if: github.event.inputs.tag_name != null
-      run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
-    - name: Get Upload URL
+    - name: Fetch required Details
       run: |
-        jq --version
-        echo "Downloading from: https://api.github.com/repos/Apicurio/apicurio-registry/releases/tags/${{ env.TAG_NAME }}"
-        echo "Alternative from: https://api.github.com/repos/Apicurio/apicurio-registry/releases/tags/$TAG_NAME"
-        UPLOAD_URL=`curl https://api.github.com/repos/Apicurio/apicurio-registry/releases/tags/${{ env.TAG_NAME }} | jq -r ".upload_url"`
-        echo "Found Upload URL: $UPLOAD_URL"
-        echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV
-    - name: Log Environment Variables
+          touch latestRelease.json && curl https://api.github.com/repos/apicurio/apicurio-registry/releases/latest > latestRelease.json
+          echo "RELEASE_VERSION=$(cat latestRelease.json | jq -r '.name')" >> $GITHUB_ENV
+          echo "SOURCE_CODE_URL=$(cat latestRelease.json | jq -r '.zipball_url')" >> $GITHUB_ENV
+          echo "UPLOAD_URL=$(cat latestRelease.json | jq -r '.upload_url')" >> $GITHUB_ENV
+    
+    - name: Echo Environment Variables
       run: |
-        echo "Tag name:   $TAG_NAME"
-        echo "Upload URL: $UPLOAD_URL"
+        echo "$RELEASE_VERSION"
+        echo "$SOURCE_CODE_URL"
+        echo "$UPLOAD_URL"
+        
+    - name: Download Source Code
+      run: wget -c $SOURCE_CODE_URL && unzip $RELEASE_VERSION && ls -lrt && mv ${{github.repository_owner}}* registry
+        
+    - name: Verify Project Version
+      run: |
+        cd registry
+        PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+        if [[ $PROJECT_VERSION != $RELEASE_VERSION ]]
+        then
+            echo "ERROR: Project Version '${PROJECT_VERSION}' does not match with Released Version '${RELEASE_VERSION}'"
+            exit 1	  
+        fi
+        
     - name: Install graalvm
       uses: DeLaGuardo/setup-graalvm@4.0
       with:
@@ -41,16 +45,22 @@ jobs:
         java: 'java11'
         # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
         arch: 'amd64'
+
     - name: Install native-image
       run: gu install native-image
+
     - name: Get maven wrapper
-      run: mvn -N io.takari:maven:wrapper -Dmaven=3.6.3
-    - name: Set version
-      run: ./mvnw versions:set -DnewVersion="$TAG_NAME"
+      run: cd registry && mvn -N io.takari:maven:wrapper -Dmaven=3.6.3
+
     - name: Build jvm jar
-      run: ./mvnw -pl cli -am install
+      run: cd registry && ./mvnw -pl cli -am install
+
     - name: Build native executable
-      run: ./mvnw -pl cli package -Dnative
+      run: cd registry && ./mvnw -pl cli package -Dnative
+      
+    - name: List Files
+      run: ls -lrt registry/cli/target/
+
     - name: Upload native executable
       id: upload-native-executable
       uses: actions/upload-release-asset@v1
@@ -58,7 +68,15 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ env.UPLOAD_URL }}
-        asset_path: ./cli/target/apicurio-registry-cli-${{ env.TAG_NAME }}-runner
-        asset_name: apicurio-registry-cli-${{ env.TAG_NAME }}-macos
+        asset_path: ./registry/cli/target/apicurio-registry-cli-${{ env.RELEASE_VERSION }}-runner
+        asset_name: apicurio-registry-cli-${{ env.RELEASE_VERSION }}-macos
         asset_label: macos
         asset_content_type: application/octet-stream
+
+    - name: Google Chat Notification
+        if: ${{ failure() }}
+        uses: Co-qn/google-chat-notification@releases/v1
+        with:
+          name: ${{ github.workflow }}
+          url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
+          status: ${{ job.status }}
