chore(operator): update a PR when the install file changes

diff --git a/.github/workflows/operator.yaml b/.github/workflows/operator.yaml
--- a/.github/workflows/operator.yaml
+++ b/.github/workflows/operator.yaml
@@ -27,16 +27,17 @@ jobs:
         run: |
           echo "UUID=$(uuidgen)" >> $GITHUB_ENV
 
-      # We need tho push the bundle image because opm always pulls; the catalog image because OLM
-      # deploys it with `imagePullPolicy: Always`; and also the operator image itself for the same reason.
-      - name: Configure env. variables 2
-        run: |
-          echo "IMAGE=ttl.sh/apicurio-registry-3-operator-$UUID:8h" >> $GITHUB_ENV
-          echo "BUNDLE_IMAGE=ttl.sh/apicurio-registry-3-operator-bundle-$UUID:8h" >> $GITHUB_ENV
-          echo "CATALOG_IMAGE=ttl.sh/apicurio-registry-3-operator-catalog-$UUID:8h" >> $GITHUB_ENV
-
       - name: Checkout ${{ github.ref }}
         uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.APICURIO_CI_GITHUB_TOKEN }}
+
+      - name: Checkout ${{ github.ref }} (PR)
+        if: github.event_name != 'push'
+        env:
+          GH_TOKEN: ${{ secrets.APICURIO_CI_GITHUB_TOKEN }}
+        run: |
+          gh pr checkout ${{ github.event.pull_request.number }}
 
       - name: Set up JDK 17
         uses: actions/setup-java@v4
@@ -58,11 +59,49 @@ jobs:
       - name: Build and run local tests on Minikube
         # Speed up the PR check by running both local and remote tests on push to main,
         # and only run remote tests against a PR.
-        # TODO: Is this ok?
         if: github.event_name == 'push'
         working-directory: operator
         run: |
           make BUILD_OPTS=--no-transfer-progress build
+
+      - name: Generate install file
+        working-directory: operator
+        run: |
+          make IMAGE_TAG=latest-snapshot INSTALL_FILE=install/install.yaml dist-install-file
+
+      - name: Update install file
+        if: github.event_name != 'push'
+        run: |
+          git add operator/install/install.yaml || true
+          if ! git diff --staged --exit-code; then
+            echo 'Install file needs to be updated. We will attempt push to the PR, otherwise please run "cd operator; make SKIP_TESTS=true build IMAGE_TAG=latest-snapshot INSTALL_FILE=install/install.yaml dist-install-file" and commit the result.'
+            git config user.name "apicurio-ci"
+            git config user.email "apicurio.ci@gmail.com"
+            git commit -m "chore(operator): update install file"
+            git push
+            exit 1
+          else
+            echo "No changes to the install file."
+          fi
+
+      - name: Check install file
+        if: github.event_name == 'push'
+        run: |
+          git add operator/install/install.yaml || true
+          if ! git diff --staged --exit-code; then
+            echo 'Install file needs to be updated. Please run "cd operator; make SKIP_TESTS=true build IMAGE_TAG=latest-snapshot INSTALL_FILE=install/install.yaml dist-install-file" and commit the result.'
+            exit 1
+          else
+            echo "No changes to the install file."
+          fi
+
+      # We need tho push the bundle image because opm always pulls; the catalog image because OLM
+      # deploys it with `imagePullPolicy: Always`; and also the operator image itself for the same reason.
+      - name: Configure env. variables 2
+        run: |
+          echo "IMAGE=ttl.sh/apicurio-registry-3-operator-$UUID:8h" >> $GITHUB_ENV
+          echo "BUNDLE_IMAGE=ttl.sh/apicurio-registry-3-operator-bundle-$UUID:8h" >> $GITHUB_ENV
+          echo "CATALOG_IMAGE=ttl.sh/apicurio-registry-3-operator-catalog-$UUID:8h" >> $GITHUB_ENV
 
       - name: Build temporary operator image
         working-directory: operator
@@ -84,46 +123,26 @@ jobs:
         run: |
           make BUILD_OPTS=--no-transfer-progress test-remote-all
 
-      - name: Update install file
-        working-directory: operator
-        run: |
-          # We need to remove unset the variables to generate a clean install file.
-          # See https://github.com/actions/runner/issues/1126
-          unset IMAGE
-          unset BUNDLE_IMAGE
-          unset CATALOG_IMAGE
-          make IMAGE_TAG=latest-snapshot INSTALL_FILE=install/install.yaml dist-install-file
-
-      - name: Check install file
-        run: |
-          git add operator/install/install.yaml || true
-          if ! git diff --staged --exit-code; then
-            echo 'Install file needs to be updated. Please run "cd operator; make SKIP_TESTS=true build IMAGE_TAG=latest-snapshot INSTALL_FILE=install/install.yaml dist-install-file" and commit the result.';
-            exit 1;
-          else
-            echo "No changes to the install file.";
-          fi
-
       # Uncomment if you need to debug the tests:
 
-#      - name: Install debug tools on failure
-#        if: failure()
-#        run: |
-#          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-#          echo >> /home/runner/.bashrc
-#          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
-#          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
-#          brew install derailed/k9s/k9s
-#          . ~/.bashrc
-#          # Run tests e.g.:
-#          # make BUILD_OPTS=--no-transfer-progress test-remote-all &> 1.log &
-#          # tail -f 1.log
-#
-#      - name: Setup tmate session on failure
-#        if: failure()
-#        uses: mxschmitt/action-tmate@v3
-#        with:
-#          limit-access-to-actor: true
+  #      - name: Install debug tools on failure
+  #        if: failure()
+  #        run: |
+  #          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+  #          echo >> /home/runner/.bashrc
+  #          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
+  #          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+  #          brew install derailed/k9s/k9s
+  #          . ~/.bashrc
+  #          # Run tests e.g.:
+  #          # make BUILD_OPTS=--no-transfer-progress test-remote-all &> 1.log &
+  #          # tail -f 1.log
+  #
+  #      - name: Setup tmate session on failure
+  #        if: failure()
+  #        uses: mxschmitt/action-tmate@v3
+  #        with:
+  #          limit-access-to-actor: true
 
   operator-publish:
     name: Publish Operator
